### ISSUE TITLE
Question on why to avoid using iron-signals 

### ISSUE THREAD

**Issue by dman777** [PolymerElements/iron-signals#10]
In the documentation, 

> Note: avoid using iron-signals whenever you can use a controller (parent element) to mediate communication instead.

For learning purposes, can you please explain why:
1) Is it strictly for readability or performance?
2) If the reason is performance, can you please give detail on what happens on a lower level and why there is a performance hit?

Thanks!

**Comment by atotic** [comment]
Not performance, readability. Signal code can be hard to understand.
