### ISSUE TITLE
QUESTION: Why is it recommended not to use iron-signals?

### ISSUE THREAD

**Issue by mikkokam** [PolymerElements/iron-signals#8]
To avoid coupling and use Polymer elements with an publish–subscribe pattern, iron-signals seems a good way to handle communication.

However, the documentation states:
> Note: avoid using iron-signals whenever you can use a controller (parent element) to mediate communication instead.

Why is this? Any specific / implementation related problems here?

Should I use another library instead for pub/sub with Polymer elements?

**Comment by atotic** [comment]
Feel free to use it for true pub-sub, there are no known implementation problems.

The warning was there for some previous usage patterns, where pub-sub made simple things complex.
